import pandas as pd
import numpy as np
import scipy.stats as stats
from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt
import io
import base64

# --- REPORT GENERATOR ENGINE ---
def fig_to_base64(fig):
    buf = io.BytesIO()
    fig.savefig(buf, format='png', bbox_inches='tight', dpi=100)
    buf.seek(0)
    img_str = base64.b64encode(buf.read()).decode('utf-8')
    return f'<img src="data:image/png;base64,{img_str}" style="max-width:100%; height:auto; border:1px solid #eee; margin: 10px 0;">'

def dataframe_to_html(df, classes='report-table'):
    if df is None: return ""
    return df.to_html(classes=classes, index=True, escape=False, float_format="{:.3f}".format)

def generate_report(title, elements):
    css_style = """
    <style>
        body { font-family: 'Segoe UI', Tahoma, sans-serif; padding: 20px; background-color: #f4f6f8; margin: 0; color: #333; }
        .report-container { 
            background: white; border-radius: 8px; box-shadow: 0 4px 15px rgba(0,0,0,0.05); 
            padding: 30px; width: 100%; max-width: 1000px; margin: 0 auto; border: 1px solid #ddd;
        }
        h1 { color: #2c3e50; text-align: center; margin-bottom: 30px; border-bottom: 2px solid #eee; padding-bottom: 15px; }
        h3 { color: #34495e; margin-top: 25px; border-left: 5px solid #3498db; padding-left: 10px; }
        p { line-height: 1.6; color: #555; }
        table.report-table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        table.report-table th, table.report-table td { padding: 10px; border: 1px solid #e0e0e0; text-align: center; }
        table.report-table th { background-color: #2c3e50; color: white; font-weight: 600; }
        table.report-table tr:nth-child(even) { background-color: #f9f9f9; }
        /* Chi-square Custom Table */
        .chi-header-var { background-color: #34495e !important; font-size: 1.1em; }
        .chi-header-val { background-color: #7f8c8d !important; }
    </style>
    """
    html = f"<!DOCTYPE html><html><head>{css_style}</head><body>"
    html += f"<div class='report-container'><h1>{title}</h1>"
    for item in elements:
        if item.get('header'): html += f"<h3>{item['header']}</h3>"
        if item['type'] == 'text': html += f"<p>{item['data']}</p>"
        elif item['type'] == 'table': html += dataframe_to_html(item['data'])
        elif item['type'] == 'raw_html': html += item['data'] # สำหรับตาราง Chi-square ที่เราสร้างเอง
        elif item['type'] == 'plot': html += f"<div style='text-align:center;'>{fig_to_base64(item['data'])}</div>"
    html += "<div style='margin-top:40px; text-align:center; color:#888; font-size:0.8em;'>Generated by Medical Stat Tool</div></div></body></html>"
    return html

# --- CALCULATION FUNCTIONS ---

def calculate_descriptive(df, col):
    if col not in df.columns: return None
    data = df[col].dropna()
    try:
        num_data = pd.to_numeric(data, errors='raise')
        desc = num_data.describe()
        return pd.DataFrame({
            "Statistic": ["Count", "Mean", "SD", "Median", "Min", "Max", "Q1", "Q3"],
            "Value": [desc['count'], desc['mean'], desc['std'], desc['50%'], desc['min'], desc['max'], desc['25%'], desc['75%']]
        }).set_index("Statistic")
    except:
        counts = data.value_counts()
        percent = data.value_counts(normalize=True) * 100
        return pd.DataFrame({"Category": counts.index, "Count": counts.values, "%": percent.values}).set_index("Category")

# 🟢 2. Chi-square Table Generator (Custom HTML)
def calculate_chi2_custom(df, row_var, col_var):
    data = df[[row_var, col_var]].dropna()
    # Crosstab พื้นฐาน
    tab = pd.crosstab(data[row_var], data[col_var])
    
    # คำนวณ Stats
    chi2, p, dof, ex = stats.chi2_contingency(tab)
    sig_text = "Significant" if p < 0.05 else "Not Significant"
    
    # สร้าง HTML Table แบบ 2 ชั้นตามที่ขอ
    # Structure:
    # --------------------------------------------------
    # |          |         Col Variable Name           |
    # | Row Name |-------------------------------------|
    # |          |    Val 1    |    Val 2    | ...     |
    # |------------------------------------------------|
    # |  Val 1   |    Count    |    Count    |         |
    # |------------------------------------------------|
    # |  Val 2   |    Count    |    Count    |         |
    # --------------------------------------------------
    
    cols = tab.columns.tolist()
    rows = tab.index.tolist()
    
    html = f"""
    <table class="report-table">
        <thead>
            <tr>
                <th rowspan="2" class="chi-header-var">{row_var}</th>
                <th colspan="{len(cols)}" class="chi-header-var">{col_var}</th>
            </tr>
            <tr>
                {''.join([f'<th class="chi-header-val">{c}</th>' for c in cols])}
            </tr>
        </thead>
        <tbody>
    """
    
    for r in rows:
        html += f"<tr><td><b>{r}</b></td>"
        for c in cols:
            val = tab.loc[r, c]
            html += f"<td>{val}</td>"
        html += "</tr>"
        
    html += "</tbody></table>"
    
    stats_info = f"<b>Chi-square statistic:</b> {chi2:.4f}, <b>P-value:</b> {p:.4e} ({sig_text})"
    return html, stats_info

# 🟢 3. T-test / ANOVA Function
def calculate_ttest(df, numeric_var, group_var):
    data = df[[numeric_var, group_var]].dropna()
    # พยายามแปลงเป็นตัวเลข
    try: data[numeric_var] = pd.to_numeric(data[numeric_var])
    except: return None, "Variable is not numeric"
    
    groups = data[group_var].unique()
    group_data = [data[data[group_var] == g][numeric_var] for g in groups]
    
    # Descriptive Table
    desc_list = []
    for g in groups:
        sub = data[data[group_var] == g][numeric_var]
        desc_list.append({
            "Group": g, "N": len(sub), "Mean": sub.mean(), "SD": sub.std(), 
            "Min": sub.min(), "Max": sub.max()
        })
    desc_df = pd.DataFrame(desc_list).set_index("Group")
    
    # Test
    if len(groups) < 2:
        return None, "Need at least 2 groups"
    elif len(groups) == 2:
        stat, p = stats.ttest_ind(group_data[0], group_data[1], equal_var=False)
        test_name = "Welch's T-test"
    else:
        stat, p = stats.f_oneway(*group_data)
        test_name = "One-way ANOVA"
        
    sig_text = "Significant" if p < 0.05 else "Not Significant"
    res_text = f"<b>{test_name}:</b> Statistic={stat:.4f}, <b>P-value={p:.4e}</b> ({sig_text})"
    
    return desc_df, res_text

# 🟢 1. ROC Analysis (Updated Output Format)
def auc_ci_hanley_mcneil(auc, n1, n2):
    q1 = auc / (2 - auc); q2 = 2 * (auc**2) / (1 + auc)
    se_auc = np.sqrt(((auc * (1 - auc)) + (n1 - 1)*(q1 - auc**2) + (n2 - 1)*(q2 - auc**2)) / (n1 * n2))
    return auc - 1.96 * se_auc, auc + 1.96 * se_auc, se_auc

def analyze_roc(df, truth_col, score_col, method='delong'):
    data = df[[truth_col, score_col]].dropna()
    y_true = pd.to_numeric(data[truth_col], errors='coerce')
    y_score = pd.to_numeric(data[score_col], errors='coerce')
    mask = y_true.notna() & y_score.notna()
    y_true = y_true[mask]; y_score = y_score[mask]

    if y_true.nunique() < 2: return None, "Outcome must have 2 classes", None, None
        
    fpr, tpr, thresholds = roc_curve(y_true, y_score)
    auc_val = roc_auc_score(y_true, y_score)
    
    j_scores = tpr - fpr
    best_idx = np.argmax(j_scores)
    best_thresh = thresholds[best_idx]
    
    # Chi-square at best cut-off
    pred_binary = (y_score >= best_thresh).astype(int)
    tab = pd.crosstab(y_true, pred_binary)
    chi2_val, p_val, _, _ = stats.chi2_contingency(tab)
    
    coords = pd.DataFrame({'Cut-off': thresholds, 'Sensitivity': tpr, 'Specificity': 1 - fpr, 'Youden Index': j_scores})
    coords = coords.sort_values(by='Youden Index', ascending=False).reset_index(drop=True)
    
    n_pos = sum(y_true == 1); n_neg = sum(y_true == 0)
    ci_lower, ci_upper, se = auc_ci_hanley_mcneil(auc_val, n_pos, n_neg)
    
    # Format Stats exactly as requested
    stats_res = {
        "AUC": auc_val,
        "95% CI Lower": max(0, ci_lower),
        "95% CI Upper": min(1, ci_upper),
        "Best Cut-off": best_thresh,
        "Sensitivity": coords.iloc[0]['Sensitivity'],
        "Specificity": coords.iloc[0]['Specificity'],
        "Youden Index": coords.iloc[0]['Youden Index'],
        "Chi-square P-value": p_val,
        "P-value Sig": "Significant" if p_val < 0.05 else "Not Significant"
    }
    
    fig, ax = plt.subplots(figsize=(6, 5), facecolor='white')
    ax.plot(fpr, tpr, color='darkorange', lw=2, label=f'AUC = {auc_val:.3f}')
    ax.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
    ax.scatter(1-stats_res['Specificity'], stats_res['Sensitivity'], color='red', s=100)
    ax.set_xlim([0.0, 1.0]); ax.set_ylim([0.0, 1.05])
    ax.set_xlabel('1 - Specificity'); ax.set_ylabel('Sensitivity')
    ax.set_title(f'ROC Curve\n(Best Cut-off: {best_thresh:.2f})')
    ax.legend(loc="lower right"); ax.grid(alpha=0.3)
    
    return stats_res, None, fig, coords
