import pandas as pd
import numpy as np
import scipy.stats as stats
from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt
import io
import base64

# --- REPORT GENERATOR ENGINE ---
def fig_to_base64(fig):
    """แปลงกราฟ Matplotlib เป็น Base64 string เพื่อฝังใน HTML"""
    buf = io.BytesIO()
    fig.savefig(buf, format='png', bbox_inches='tight', dpi=100)
    buf.seek(0)
    img_str = base64.b64encode(buf.read()).decode('utf-8')
    return f'<img src="data:image/png;base64,{img_str}" style="max-width:100%; height:auto; border:1px solid #eee; margin: 10px 0;">'

def dataframe_to_html(df):
    """แปลง DataFrame เป็น HTML Table สไตล์ Paper"""
    if df is None: return ""
    return df.to_html(classes='report-table', index=False, escape=False, float_format="{:.3f}".format)

def generate_report(title, elements):
    """
    สร้าง HTML Report สวยๆ รองรับ ตาราง, ข้อความ, และกราฟ
    elements = list of dict: {'type': 'table'|'text'|'plot', 'header': str, 'data': object}
    """
    # CSS Styling (Theme เดียวกับ Table 1)
    css_style = """
    <style>
        body { font-family: 'Segoe UI', Tahoma, sans-serif; padding: 20px; background-color: #f4f6f8; margin: 0; color: #333; }
        .report-container { 
            background: white; 
            border-radius: 8px; 
            box-shadow: 0 4px 15px rgba(0,0,0,0.05); 
            padding: 30px;
            width: 100%; 
            max-width: 1000px;
            margin: 0 auto;
            border: 1px solid #ddd;
            box-sizing: border-box;
        }
        h1 { color: #2c3e50; text-align: center; margin-bottom: 30px; font-size: 1.8em; border-bottom: 2px solid #eee; padding-bottom: 15px; }
        h3 { color: #34495e; margin-top: 25px; border-left: 5px solid #3498db; padding-left: 10px; font-size: 1.2em; }
        p { line-height: 1.6; color: #555; }
        
        /* Table Styling */
        table.report-table { width: 100%; border-collapse: collapse; margin: 15px 0; font-size: 0.95em; }
        table.report-table th { background-color: #2c3e50; color: white; padding: 12px; text-align: left; font-weight: 600; border: 1px solid #34495e; }
        table.report-table td { padding: 10px; border: 1px solid #e0e0e0; color: #333; vertical-align: top; }
        table.report-table tr:nth-child(even) { background-color: #f9f9f9; }
        table.report-table tr:hover { background-color: #f1f7ff; }
        
        .footer { margin-top: 40px; text-align: center; font-size: 0.8em; color: #888; border-top: 1px solid #eee; padding-top: 20px; }
    </style>
    """
    
    html = f"<!DOCTYPE html><html><head>{css_style}</head><body>"
    html += f"<div class='report-container'><h1>{title}</h1>"
    
    for item in elements:
        if item.get('header'):
            html += f"3>{item['header']}</h3>"
        
        if item['type'] == 'text':
            html += f"<p>{item['data']}</p>"
            
        elif item['type'] == 'table':
            html += dataframe_to_html(item['data'])
            
        elif item['type'] == 'plot':
            html += f"<div style='text-align:center;'>{fig_to_base64(item['data'])}</div>"
            
    html += "<div class='footer'>Generated by Medical Stat Tool</div></div></body></html>"
    return html

# --- CALCULATION FUNCTIONS (คงเดิมแต่ return raw data) ---

def calculate_descriptive(df, col):
    if col not in df.columns: return None
    data = df[col].dropna()
    try:
        num_data = pd.to_numeric(data, errors='raise')
        desc = num_data.describe()
        return pd.DataFrame({
            "Statistic": ["Count", "Mean", "SD", "Median", "Min", "Max", "Q1", "Q3"],
            "Value": [desc['count'], desc['mean'], desc['std'], desc['50%'], desc['min'], desc['max'], desc['25%'], desc['75%']]
        })
    except:
        counts = data.value_counts()
        percent = data.value_counts(normalize=True) * 100
        return pd.DataFrame({"Category": counts.index, "Count": counts.values, "Percentage (%)": percent.values})

def calculate_chi2(df, col1, col2):
    data = df[[col1, col2]].dropna()
    tab = pd.crosstab(data[col1], data[col2])
    try:
        chi2, p, dof, ex = stats.chi2_contingency(tab)
        msg = f"Chi-square statistic: {chi2:.4f}, P-value: {p:.4f}"
        return tab, msg
    except Exception as e: return None, str(e)

def auc_ci_hanley_mcneil(auc, n1, n2):
    q1 = auc / (2 - auc); q2 = 2 * (auc**2) / (1 + auc)
    se_auc = np.sqrt(((auc * (1 - auc)) + (n1 - 1)*(q1 - auc**2) + (n2 - 1)*(q2 - auc**2)) / (n1 * n2))
    return auc - 1.96 * se_auc, auc + 1.96 * se_auc, se_auc

def analyze_roc(df, truth_col, score_col, method='delong'):
    # (Logic เดิม)
    data = df[[truth_col, score_col]].dropna()
    y_true = pd.to_numeric(data[truth_col], errors='coerce')
    y_score = pd.to_numeric(data[score_col], errors='coerce')
    mask = y_true.notna() & y_score.notna()
    y_true = y_true[mask]; y_score = y_score[mask]

    if y_true.nunique() < 2: return None, "Outcome must have 2 classes (0/1)", None, None
        
    fpr, tpr, thresholds = roc_curve(y_true, y_score)
    auc_val = roc_auc_score(y_true, y_score)
    
    j_scores = tpr - fpr
    best_idx = np.argmax(j_scores)
    best_thresh = thresholds[best_idx]
    
    pred_binary = (y_score >= best_thresh).astype(int)
    tab = pd.crosstab(y_true, pred_binary)
    _, p_val, _, _ = stats.chi2_contingency(tab)
    
    coords = pd.DataFrame({'Cut-off': thresholds, 'Sensitivity': tpr, 'Specificity': 1 - fpr, 'Youden Index': j_scores})
    
    # PPV NPV
    n_pos = sum(y_true == 1); n_neg = sum(y_true == 0)
    tps = tpr * n_pos; fps = fpr * n_neg; tns = n_neg - fps; fns = n_pos - tps
    with np.errstate(divide='ignore', invalid='ignore'):
        coords['PPV'] = tps / (tps + fps)
        coords['NPV'] = tns / (tns + fns)
    
    coords = coords.sort_values(by='Youden Index', ascending=False).reset_index(drop=True)
    
    # CI
    ci_lower, ci_upper, se = auc_ci_hanley_mcneil(auc_val, n_pos, n_neg)
    ci_lower = max(0, ci_lower); ci_upper = min(1, ci_upper)
    
    stats_res = {
        "AUC": auc_val,
        "95% CI": f"{ci_lower:.3f} - {ci_upper:.3f}",
        "Best Cut-off": best_thresh,
        "Sensitivity": coords.iloc[0]['Sensitivity'],
        "Specificity": coords.iloc[0]['Specificity'],
        "Youden Index": coords.iloc[0]['Youden Index'],
        "Chi-square P-value": p_val
    }
    
    # Plot (ตั้งค่าสีขาวที่นี่ด้วยเพื่อความชัวร์)
    fig, ax = plt.subplots(figsize=(6, 5), facecolor='white')
    ax.plot(fpr, tpr, color='darkorange', lw=2, label=f'AUC = {auc_val:.3f}')
    ax.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
    ax.scatter(1-stats_res['Specificity'], stats_res['Sensitivity'], color='red', s=100, label=f'Best Cut-off ({best_thresh:.2f})')
    ax.set_xlim([0.0, 1.0]); ax.set_ylim([0.0, 1.05])
    ax.set_xlabel('1 - Specificity'); ax.set_ylabel('Sensitivity')
    ax.set_title('ROC Curve Analysis')
    ax.legend(loc="lower right"); ax.grid(alpha=0.3)
    
    return stats_res, None, fig, coords
